### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by Maxpain177** [meteorhacks/cluster#52]
Sometimes my app throws that error:
```
Cluster: Exiting worker 2 with exitCode=7 signalCode=null
Error: write after end
    at writeAfterEnd (_stream_writable.js:133:12)
    at Socket.Writable.write (_stream_writable.js:181:5)
    at Socket.write (net.js:616:40)
    at Socket.Writable.end (_stream_writable.js:341:10)
    at Socket.end (net.js:397:31)
    at App.exports.GenericApp.GenericApp.handle_error (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/webjs.js:148:13)
    at execute_request (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/webjs.js:33:30)
    at Object.req.next_filter (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/webjs.js:105:18)
    at Listener.webjs_handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/webjs.js:107:13)
    at Listener.handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:147:12)
```

**Comment by arunoda** [comment]
Okay. I will look into this.

**Comment by arunoda** [comment]
Did a new release. With that this should get fixed.
