### ISSUE TITLE
Cluster: no such endpoint for service

### ISSUE THREAD

**Issue by aykutyaman** [meteorhacks/cluster#56]
I have 3 servers deployment on AWS. Sometimes one of my servers returns 404s for socks.js requests like this: /sockjs/info?cb=_4xxw5rmad
And my app in that server stops to function.
Servers' upstart log is plenty of these lines:
```
Kadira: Error sending payload (dropped after 5 tries) undefined
Cluster: no such endpoint for service:notification
Cluster: no such endpoint for service:notification
Cluster: no such endpoint for service:web
Cluster: there is no endpoint but we've a hash: f3439f2f4d2dc847b6f86d2580f721107277dd64
Cluster: there is no endpoint but we've a hash: f3439f2f4d2dc847b6f86d2580f721107277dd64
```
I can't even display my server ip under the hosts' selectbox of kadira.

**Comment by aykutyaman** [comment]
I found this exception today in the logs.
```
Exception in setTimeout callback: TypeError: Cannot read property 'serviceName' of undefined^M
    at MongoDiscoveryStore.remove (packages/meteorhacks:cluster/lib/server/discovery_backends/mongo/store.js:37:1)^M
    at packages/meteorhacks:cluster/lib/server/discovery_backends/mongo/discovery.js:239:1^M
    at Array.forEach (native)^M
    at fecthAndWatch (packages/meteorhacks:cluster/lib/server/discovery_backends/mongo/discovery.js:237:1)^M
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)^M
    at packages/meteor/timers.js:6:1^M
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)^M
```

**Comment by arunoda** [comment]
Fixed with `4e0d719`.
Will do a fix soon.
