### ISSUE TITLE
Cannot read property 'writeHead' of undefined

### ISSUE THREAD

**Issue by Maxpain177** [meteorhacks/cluster#93]
```
[151.80.36.183] Sikka: IP Blocked. XXX.XXX.XXX.XXX
[151.80.36.183] Sikka: Closing current connection xwezeMPk88xQKgrPv
[151.80.36.183] Tue, 15 Sep 2015 12:55:17 GMT uncaughtException: Cannot read property 'writeHead' of undefined
[151.80.36.183] TypeError: Cannot read property 'writeHead' of undefined
    at Listener.webjs_handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/webjs.js:78:21)
    at Listener.handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:147:12)
    at Listener.handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:6:61)
    at Server.<anonymous> (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:154:24)
    at Server.new_handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/utils.js:86:19)
    at packages/ddp/stream_server.js:133:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Server.newListener (packages/ddp/stream_server.js:132:1)
    at packages/meteorhacks:cluster/lib/server/utils.js:11:1
[151.80.36.183] TypeError: Cannot read property 'writeHead' of undefined
    at Listener.webjs_handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/webjs.js:78:21)
    at Listener.handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:147:12)
    at Listener.handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:6:61)
    at Server.<anonymous> (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/sockjs.js:154:24)
    at Server.new_handler (/opt/easydrop/app/programs/server/npm/ddp/node_modules/sockjs/lib/utils.js:86:19)
    at packages/ddp/stream_server.js:133:1
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at Server.newListener (packages/ddp/stream_server.js:132:1)
    at packages/meteorhacks:cluster/lib/server/utils.js:11:1
[151.80.36.183] Cluster: Exiting worker 3 with exitCode=7 signalCode=null
[151.80.36.183] Cluster: Initializing worker 10 on port 17442

```

How to fix it?

**Comment by Maxpain177** [comment]
please fix it, It happens quite often

**Comment by Maxpain177** [comment]
ясно
